debian: Guard against udevadm failure
Check for udevadm failures in Debian postinst/postrm, warn about them,
but otherwise ignore, as recommended by lintian.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,7 +4,9 @@ set -e
 
 case "$1" in
     configure)
-	udevadm control --reload
+        if ! udevadm control --reload; then
+            echo "udevadm control --reload failed, ignoring" >&2
+        fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -4,7 +4,9 @@ set -e
 
 case "$1" in
     purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-	udevadm control --reload
+        if ! udevadm control --reload; then
+            echo "udevadm control --reload failed, ignoring" >&2
+        fi
     ;;
 
     *)
